### PR TITLE
Add missing hex related attributes to app.src in preparation for a publication on hex.pm

### PR DESCRIPTION
**Pull request by drobakowski**
Like discussed in https://github.com/bipthelin/mochiweb_util/issues/1, I've added some missing `app.src` attributes for a publication on hex.pm. I had to add a license attribute as this is required form hex. I've chosen the MIT license as it seems that you are using it most of the times, I hope this was ok?

After the the merge you should be able to publish this package on hex.pm like described in the [documentation](https://hex.pm/docs/rebar3_publish).

### CODE REVIEW

**Comment by bipthelin** [comment]
Thanks

**Comment by drobakowski** [comment]
@bipthelin sorry to bother you. Do you still have any plans to publish this lib on hex.pm in preparation for also publishing https://github.com/kivra/restclient? Alternatively I could do it like Heinz did with https://github.com/kivra/oauth2/pull/63, but I think it would be better to have this directly published over a Kivra account.

**Comment by bipthelin** [comment]
Done

**Comment by drobakowski** [comment]
Great, thanks @bipthelin!

**Pull request merged**
